@server = http://localhost:4000/api
@e1 = temp4@temp.com
@p1 = password123

##### User Auth and Info
### sign up
POST {{server}}/auth/sign-up/email

{
  "name": "Test User",
  "email": "{{e1}}",
  "password": "{{p1}}"
}

### sign in
POST {{server}}/auth/sign-in/email

{
  "email": "{{e1}}",
  "password": "{{p1}}"
}
### sign out
POST {{server}}/auth/sign-out

### get user info
GET {{server}}/user

### get settings
GET {{server}}/user/settings

### get stats
GET {{server}}/user/stats

### update settings
PATCH {{server}}/user/settings

{
  "soundEnabled": true,
  "typingSoundEnabled": true
}

##### Tests
### Complete test
POST {{server}}/test/

{
  "wpm": 128,
  "rawWpm": 130,
  "accuracy": 98.75,
  "correctChars": 150,
  "errorChars": 10,
  "time": 33,
  "wordsTyped": 60,
  "mode": "words"
}

### Delete test
DELETE {{server}}/test/

{
  "testId": "yo123"
}

##### PvP
### Host
POST {{server}}/pvp/host/

{
  "private": true
}
### Get Match status
POST {{server}}/pvp/room-status/

{
  "roomCode": "yo123"
}
