@server = http://localhost:3001/api
@e1 = temp4@temp.com
@p1 = password123

### sign up
POST {{server}}/auth/sign-up/email

{
  "name": "Test User",
  "email": "{{e1}}",
  "password": "{{p1}}"
}

### sign in
POST {{server}}/auth/sign-in/email

{
  "email": "{{e1}}",
  "password": "{{p1}}"
}
### sign out
POST {{server}}/auth/sign-out

### get user info
GET {{server}}/user

### get settings
GET {{server}}/user/settings

### get stats
GET {{server}}/user/stats
